export default dummyData = [
    {
      id: "1",
      name: "The Italian Bistro",
      address: "123 Pasta Lane, Roma",
      contactInfo: "555-1234",
      description: "Authentic Italian cuisine with a variety of pasta dishes.",
      hours: {
        sunday: { opening: "10:00 AM", closing: "10:00 PM" },
        monday: { opening: "10:00 AM", closing: "10:00 PM" },
        tuesday: { opening: "10:00 AM", closing: "10:00 PM" },
        wednesday: { opening: "10:00 AM", closing: "10:00 PM" },
        thursday: { opening: "10:00 AM", closing: "10:00 PM" },
        friday: { opening: "10:00 AM", closing: "11:00 PM" },
        saturday: { opening: "10:00 AM", closing: "11:00 PM" },
      },
      photos: ["image1.jpg", "image2.jpg"],
      category: ["Italian", "Vegetarian"],
      priceRange: "Medium",
      file: null,
      latitude: "41.9028",
      longitude: "12.4964",
    },
    {
      id: "2",
      name: "Sushi World",
      address: "456 Fish Street, Tokyo",
      contactInfo: "555-5678",
      description: "Sushi and sashimi served fresh daily.",
      hours: {
        sunday: { opening: "11:00 AM", closing: "9:00 PM" },
        monday: { opening: "11:00 AM", closing: "9:00 PM" },
        tuesday: { opening: "11:00 AM", closing: "9:00 PM" },
        wednesday: { opening: "11:00 AM", closing: "9:00 PM" },
        thursday: { opening: "11:00 AM", closing: "9:00 PM" },
        friday: { opening: "11:00 AM", closing: "10:00 PM" },
        saturday: { opening: "11:00 AM", closing: "10:00 PM" },
      },
      photos: ["sushi1.jpg", "sushi2.jpg"],
      category: ["Japanese", "Seafood"],
      priceRange: "High",
      file: null,
      latitude: "35.6762",
      longitude: "139.6503",
    },
    {
      id: "3",
      name: "Burger Haven",
      address: "789 Burger Blvd, NYC",
      contactInfo: "555-9101",
      description: "The best burgers in town, made fresh to order.",
      hours: {
        sunday: { opening: "9:00 AM", closing: "11:00 PM" },
        monday: { opening: "9:00 AM", closing: "11:00 PM" },
        tuesday: { opening: "9:00 AM", closing: "11:00 PM" },
        wednesday: { opening: "9:00 AM", closing: "11:00 PM" },
        thursday: { opening: "9:00 AM", closing: "11:00 PM" },
        friday: { opening: "9:00 AM", closing: "12:00 AM" },
        saturday: { opening: "9:00 AM", closing: "12:00 AM" },
      },
      photos: ["burger1.jpg", "burger2.jpg"],
      category: ["American", "Fast Food"],
      priceRange: "Medium",
      file: null,
      latitude: "40.7128",
      longitude: "-74.0060",
    },
    {
      id: "4",
      name: "The Italian Bistro", // Duplicate of the first entry
      address: "123 Pasta Lane, Roma",
      contactInfo: "555-1234",
      description: "Authentic Italian cuisine with a variety of pasta dishes.",
      hours: {
        sunday: { opening: "10:00 AM", closing: "10:00 PM" },
        monday: { opening: "10:00 AM", closing: "10:00 PM" },
        tuesday: { opening: "10:00 AM", closing: "10:00 PM" },
        wednesday: { opening: "10:00 AM", closing: "10:00 PM" },
        thursday: { opening: "10:00 AM", closing: "10:00 PM" },
        friday: { opening: "10:00 AM", closing: "11:00 PM" },
        saturday: { opening: "10:00 AM", closing: "11:00 PM" },
      },
      photos: ["image1.jpg", "image2.jpg"],
      category: ["Italian", "Vegetarian"],
      priceRange: "Medium",
      file: null,
      latitude: "41.9028",
      longitude: "12.4964",
    },
    {
      id: "5",
      name: "Taco Fiesta",
      address: "101 Taco Lane, Mexico City",
      contactInfo: "555-2345",
      description: "Delicious tacos, burritos, and more Mexican dishes.",
      hours: {
        sunday: { opening: "10:00 AM", closing: "9:00 PM" },
        monday: { opening: "10:00 AM", closing: "9:00 PM" },
        tuesday: { opening: "10:00 AM", closing: "9:00 PM" },
        wednesday: { opening: "10:00 AM", closing: "9:00 PM" },
        thursday: { opening: "10:00 AM", closing: "9:00 PM" },
        friday: { opening: "10:00 AM", closing: "10:00 PM" },
        saturday: { opening: "10:00 AM", closing: "10:00 PM" },
      },
      photos: ["taco1.jpg", "taco2.jpg"],
      category: ["Mexican", "Vegetarian"],
      priceRange: "Low",
      file: null,
      latitude: "19.4326",
      longitude: "-99.1332",
    },
    {
      id: "6",
      name: "Sushi World", // Duplicate of the second entry
      address: "456 Fish Street, Tokyo",
      contactInfo: "555-5678",
      description: "Sushi and sashimi served fresh daily.",
      hours: {
        sunday: { opening: "11:00 AM", closing: "9:00 PM" },
        monday: { opening: "11:00 AM", closing: "9:00 PM" },
        tuesday: { opening: "11:00 AM", closing: "9:00 PM" },
        wednesday: { opening: "11:00 AM", closing: "9:00 PM" },
        thursday: { opening: "11:00 AM", closing: "9:00 PM" },
        friday: { opening: "11:00 AM", closing: "10:00 PM" },
        saturday: { opening: "11:00 AM", closing: "10:00 PM" },
      },
      photos: ["sushi1.jpg", "sushi2.jpg"],
      category: ["Japanese", "Seafood"],
      priceRange: "High",
      file: null,
      latitude: "35.6762",
      longitude: "139.6503",
    },
  ];
  